### ISSUE TITLE
Update Website Mockup to include date section for the feed page

### ISSUE THREAD

**Issue by TeddyCr** [hackla-engage/engage-client#106]
The feed page should include a date section to ease the user flow while scrolling through items. Current mockups can be find [here](https://projects.invisionapp.com/share/SXLOB9IJQ4K#/screens/304303934). 

---
To get login information reach out to @owenjoseph or @TeddyCr

**Comment by TeddyCr** [comment]
When updating the mockup, we should also remove the "filed under" section as this is not something we currently want to support.

**Comment by owenjoseph** [comment]
@TeddyCr can this be closed? Matina has provided a new working prototype (needs to be added to the Product Wiki)

https://www.figma.com/proto/WF9WwFRo32unFwXuPh4kEP7U/Mobile?node-id=10%3A7&viewport=-1319%2C-218%2C0.5&scaling=fit-width&redirected=1
