### ISSUE TITLE
Add a Date Section/Title Grouping Agenda Items per Dates on /feed

### ISSUE THREAD

**Issue by TeddyCr** [hackla-engage/engage-client#107]
The agenda items should be grouped under a date section/title to ease user navigation. Refer to #106 for mockup.

**Comment by vzcode** [comment]
Hi there @TeddyCr - on this ticket, from what I see on local, the items are already chronologically set (most recent first), and the mock https://projects.invisionapp.com/share/SXLOB9IJQ4K#/screens/304303934 also shows each agenda item listed most recent first. 

Is this issue to style the /feed page to look like the mock? Or is there another mock that groups all agenda items for 10/23 (for instance) together?

**Comment by TeddyCr** [comment]
@vzcode the idea is to add a title section that would group the agenda items with the same date together. Unfortunately I don't have an  updated mock but it would look something like that

**10/23/2018 - 5:30PM**
---------------------------

+---------------------------------------+
|                                  Meeting date    |
|                                  10/23/2018       |
|                                  5:30PM             |
+---------------------------------------+
|   SOMETHING                                    |
+---------------------------------------+
|    View Items                                      |
+---------------------------------------+

+---------------------------------------+
|                                  Meeting date    |
|                                  10/23/2018       |
|                                  5:30PM             |
+---------------------------------------+
|   SOMETHING                                    |
+---------------------------------------+
|    View Items                                      |
+---------------------------------------+

**10/12/2018 - 5:30PM**
---------------------------


+---------------------------------------+
|                                  Meeting date    |
|                                  10/12/2018       |
|                                  5:30PM             |
+---------------------------------------+
|   SOMETHING                                    |
+---------------------------------------+
|    View Items                                      |
+---------------------------------------+

+---------------------------------------+
|                                  Meeting date    |
|                                  10/12/2018       |
|                                  5:30PM             |
+---------------------------------------+
|   SOMETHING                                    |
+---------------------------------------+
|    View Items                                      |
+---------------------------------------+

Effectively the agenda items will not change format, we'll just add a title section to make it visually more clear that these agenda items are for this date.

Let me know if you have any questions

------

cc @owenjoseph

**Comment by vzcode** [comment]
Ah awesome - this itself is super helpful, thanks @TeddyCr. I'll be looking into this tomorrow and seeing what I can do.

**Comment by vzcode** [comment]
Hi @TeddyCr this is where I have it thus far as a screenshot - please let me know what your thoughts are (until I have the ability to push up a branch) 
![screenshot 2018-11-08 15 15 05](https://user-images.githubusercontent.com/362589/48233237-5318b700-e369-11e8-81b7-cb1ca4b5eafa.png)

**Comment by TeddyCr** [comment]
@vzcode have you ever checked the revision request on the PR?

**Comment by TeddyCr** [comment]
removing @vzcode from owner of this issue as he has not been responsive.

**Comment by owenjoseph** [comment]
@TeddyCr This looks to be merged with both staging and prod already. Closing.
