### ISSUE TITLE
Limit Agenda Item Display to Most Recent Date on /feed Load

### ISSUE THREAD

**Issue by TeddyCr** [hackla-engage/engage-client#108]
The feed page should only display the most recent agenda items on load. The Load More button at the bottom of the page will remain. When clicking on it, users should be able to load previous agenda items.

**Comment by owenjoseph** [comment]
@TeddyCr there's a chance the city may post more than one meeting's agenda items, in which case the next upcoming dates – which would be the most relevant – would end up falling below the "load more" button. What are your thoughts on removing the MVP tag from this one? It's not really "breaking" the functionality right now.

**Comment by TeddyCr** [comment]
Make sense. I am gonna label it as backlog for now. We can come back to it later and think of a solution for what you mentioned.
