### ISSUE TITLE
Bug: Item details page does not load at top of page

### ISSUE THREAD

**Issue by kayteecannon** [hackla-engage/engage-client#126]
Item details page does not load at top of page when user selects an issue after scrolling down  1. Scroll down page to select issue not already on screen on initial load. 2. Click on the issue. 3. The page does not load with the scroll bar at the top of the item details page.

**Comment by hungrymonkey** [comment]
https://stackoverflow.com/questions/33188994/scroll-to-the-top-of-the-page-after-render-in-react-js

```
componentDidUpdate() {
  ReactDOM.findDOMNode(this).scrollTop = 0
},
``
Can be fixed by adding a function to componentDidUpdate, but we have to check the back behavior.

**Comment by TeddyCr** [comment]
@hungrymonkey was that ever solved?

**Comment by joshbeme** [comment]
I was able to fix this.
