### ISSUE TITLE
Add more prominent link to "HowTo" component from Splash page

### ISSUE THREAD

**Issue by owenjoseph** [hackla-engage/engage-client#127]
Currently our splash page has one prominent link, which routes to our main feed:

![splash-page-current](https://user-images.githubusercontent.com/39287217/46704878-dc5d9200-cbe1-11e8-9439-d1106cfd3c27.png)

We'd like to add a prominent call to action targeted at new users of the site, directing them to the 'HowTo' component:

![splash-page-add-button](https://user-images.githubusercontent.com/39287217/46704896-eed7cb80-cbe1-11e8-87cf-f5797b969041.png)

The new button styling should match the styling of the current 'Engage' button, though with a more muted color (the "Start Engaging" button should remain the most prominent element).

Tag @owenjoseph (me) if you have questions!

**Comment by jbmills327** [comment]
I'd like to take a crack at this if that's ok.

**Comment by owenjoseph** [comment]
Hey @jbmills327 yeah go for it. Thanks!

**Comment by TicoGitHubII** [comment]
Is there any update on this issue is it still open?

**Comment by ndrwmp** [comment]
> Is there any update on this issue is it still open?

Ah, no. I ended up joining the heart app so I never got to this. Still open.

**Comment by TicoGitHubII** [comment]
ok thanks

**Comment by owenjoseph** [comment]
Hey @TicoGitHubII thanks for investigating this. Let me know if you have any questions.

**Comment by TicoGitHubII** [comment]
I'm in the process of requesting a pull for this issue

**Comment by TicoGitHubII** [comment]
@owenjoseph 
let me know what you link on the changes

**Comment by owenjoseph** [comment]
Found the commit with @TicoGitHubII's button add - going to work on reincorporating this into Landing.jsx tonight / this week if I don't get to it.
