### ISSUE TITLE
User should see alt Splash Text when no active issues are available

### ISSUE THREAD

**Issue by owenjoseph** [hackla-engage/engage-client#135]
## Description
When there are no active issues on the Engage feed – i.e. all displayed Agenda Items are for meetings which have already occurred – users should be presented with:
- An explanation of why voting will be closed for all displayed agenda items, and
- Option(s) to subscribe to various services that will update them when new agenda items are scraped

## Acceptance Criteria
- When all agenda items are in the past, the user should see the following:
![proposed_alt_splash-01](https://user-images.githubusercontent.com/39287217/49410422-5cebcb00-f719-11e8-9ce0-5253658d2a84.png)
- the text "@EngageStaMonica" should link to: https://twitter.com/EngageStaMonica
- the [MailChimpSignupForm] should be replaced with:

```
<!-- Begin Mailchimp Signup Form -->
<link href="//cdn-images.mailchimp.com/embedcode/classic-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
	/* Add your own Mailchimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="https://hackforla.us19.list-manage.com/subscribe/post?u=2885093b7df42c79d628f7267&amp;id=6ca892a88b" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	
<div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
<div class="mc-field-group">
	<label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
</label>
	<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
<div class="mc-field-group">
	<label for="mce-FNAME">First Name </label>
	<input type="text" value="" name="FNAME" class="" id="mce-FNAME">
</div>
<div class="mc-field-group">
	<label for="mce-LNAME">Last Name </label>
	<input type="text" value="" name="LNAME" class="" id="mce-LNAME">
</div>
<div class="mc-field-group input-group">
    <strong>Email Format </strong>
    <ul><li><input type="radio" value="html" name="EMAILTYPE" id="mce-EMAILTYPE-0"><label for="mce-EMAILTYPE-0">html</label></li>
<li><input type="radio" value="text" name="EMAILTYPE" id="mce-EMAILTYPE-1"><label for="mce-EMAILTYPE-1">text</label></li>
</ul>
</div>
	<div id="mce-responses" class="clear">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_2885093b7df42c79d628f7267_6ca892a88b" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>
<script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';fnames[3]='ADDRESS';ftypes[3]='address';fnames[4]='PHONE';ftypes[4]='phone';}(jQuery));var $mcj = jQuery.noConflict(true);</script>
<!--End mc_embed_signup-->
```
- When active issues ARE present, the user should see **NONE** of the above

## Styling
**Please match styling on Feed component, not styling in mockup image.**

**Comment by joshbeme** [comment]
Is there a way to find the next date for city council meetings through the api or should I leave it as "DAY-MONTH-YEAR-TIME" for now? It seems that the agendas endpoint only gives agendas to March 26th 2019.

**Comment by joshbeme** [comment]
Is the forms action suppose to link to the hack for la news letter?

**Comment by joshbeme** [comment]
![no-active-issuees](https://user-images.githubusercontent.com/38735622/55270095-269e0280-5258-11e9-9539-16cf83c42a14.png)
 This is what I have so far for this. I was wondering if I needed to add recaptcha to it?

**Comment by owenjoseph** [comment]
@joshbeme I'm ok with leaving recaptcha out of scope for now and adding later if needed.

The forms action shouldn't link to the Hack for L.A. newsletter; it should link to the Engage Mailchimp signup. It's weird, I thought I copied the embed code above directly from the Engage mailchip account. . . let me double check that.

If there's no way to get upcoming meeting dates from the API endpoint currently, let's remove that language for now. So the first line after "there are no active issues. . . " would be "To be notified when issues become available. . . "

**Comment by owenjoseph** [comment]
@joshbeme yeah that link in the form is correct:

https://hackforla.us19.list-manage.com/subscribe/post?u=2885093b7df42c79d628f7267&amp;id=6ca892a88b

I originally signed up for our account using "Hack for L.A." as our organization name; looks like MC uses that field to generate the signup subdomain in the URL. We'll keep it that way for now.

**Comment by owenjoseph** [comment]
@joshbeme since adding the date/time for the upcoming meeting would require building a new scraper, I'm going to remove that from the AC for this issue. Since everything else has been merged with staging, I'm moving this to the Staging column.
