### ISSUE TITLE
Improvements to Landing Page - change background image, add some helpful copy

### ISSUE THREAD

**Issue by owenjoseph** [hackla-engage/engage-client#144]
As a new Engage user, I'd like to learn more from the Engage landing page before I continue on to the feed.

- There is a potential here to do more than tell a visitor to "start Engaging"; some contextualizing copy would be helpful, e.g.: a mission-statement or elevator pitch
- The background image (stock) doesn't communicate anything about the purpose of the site or the locality

Action Items:
- propose text
- find a new dang image!

**Comment by TeddyCr** [comment]
Addressed in #169
