### ISSUE TITLE
Change much -> must Readme

### ISSUE THREAD

**Issue by hungrymonkey** [hackla-engage/engage-client#152]
https://github.com/hackla-engage/engage-client/blob/staging/README.md

In contributing, documentation is wrong

> All PR much be committed to staging

should be

> All PR must be committed to staging

Steps to fix
Fork engage-client/staging
```
git clone <engage-client-url>
git checkout staging
git checkout -b fix-readme-issue-152
```
Fix the Read me
```
Edit in text editor and save
```
Commit fix to your repository
```
git commit -m  "I fixed issue #152"
git  push --set-upstream origin fix-readme-issue-152
```
Send pr request to review.
```
Go to github.com and set up pull request
```
Please link pull request to this issue so it might automatically close

**Comment by TeddyCr** [comment]
PR #162
