### ISSUE TITLE
Null agendaItems should display a default message

### ISSUE THREAD

**Issue by owenjoseph** [hackla-engage/engage-client#170]
Users should not see empty agendaItems when they click to see more details. 

E.g.: 
![Screen Shot 2019-05-06 at 7 02 11 PM](https://user-images.githubusercontent.com/39287217/57266643-ba21da80-7031-11e9-9b98-2ecec06901d1.png)

The city website version of which looks like: 
![Screen Shot 2019-05-06 at 7 02 21 PM](https://user-images.githubusercontent.com/39287217/57266647-c017bb80-7031-11e9-9869-205dff59552a.png)

**Comment by TeddyCr** [comment]
@owenjoseph, I don't think it should not be rendered. I think a default text should be added instead (i.e. "The city has not provided any executive summary/recommendations for this agenda item. Though, you can still vote and comment on this issue."), something along these lines.

It will still addressed during the meeting, in my opinion I think it should still appear on the site.

**Comment by owenjoseph** [comment]
@TeddyCr I think this was actually solved? If you look at what was scraped for June 25th, the first item from the city's agenda is "SMTT FY19-20 Work Plan and Budget", which is Item 3c from the agenda.

This is appropriate because it's the first item with a recommended action.
