### ISSUE TITLE
Remove character limit from "comment" field in agenda feedback form

### ISSUE THREAD

**Issue by owenjoseph** [hackla-engage/engage-client#171]
User should be able to type as many words as they need to get their point across. Additionally, the city considers a character limit to be a 1st amendment infringement(!).

![Screenshot_5_6_19__7_56_PM](https://user-images.githubusercontent.com/39287217/57269404-2acdf480-703c-11e9-89cc-9b7331dfd2dc.png)

Acceptance criteria - no (practical) limit to text entry.

**Comment by eselkin** [comment]
The practical limit may be the type we have in the backend. I'll check.

**Comment by eselkin** [comment]
So yes, we have a problem, the DB is using a constrained character type (VARCHAR(254))... We'll have to bring the DB down to change this.

**Comment by TicoGitHubII** [comment]
has anyone worked on this ?

**Comment by owenjoseph** [comment]
Hey @TicoGitHubII I think this one is still in need of help. Please coordinate with @eliselkin if you have the bandwidth to tackle this this week. . . if it's going to require site downtime It would be good to work around our active issues window (e.g., next meeting is Tuesday, July 9th: moratorium on downtime should be between Friday, July 5th and the 9th).

**Comment by eselkin** [comment]
The backend has removed the character limit, it is now a textfield with no text limit.

**Comment by eselkin** [comment]
July 9th meeting was cancelled

**Comment by ldaws003** [comment]
Is this issue still open?

**Comment by eselkin** [comment]
Let me check...

**Comment by eselkin** [comment]
Yeah it's still there in staging: https://github.com/hackla-engage/engage-client/blob/c3b048407fcd6cf1703b22e9bc3f424680c74f40/src/component/CommentForm.jsx#L337

**Comment by ldaws003** [comment]
Alright, thanks. I'll work on it as soon as I can. Also I noticed that there was a way to assign yourself tasks on the to do list in the project section on the engage github. How do I assign a task to myself?

**Comment by eselkin** [comment]
@ldaws003 completed this in #190
