### ISSUE TITLE
Update scrape to exclude "Special Agenda Items"

### ISSUE THREAD

**Issue by owenjoseph** [hackla-engage/engage-client#172]
Currently the Feed is displaying, with priority, items from
 **"2.	SPECIAL AGENDA ITEMS"**
These items are not suitable for feedback, and are typically contentless:

![screen shot 2018-11-26 at 8 15 29 pm](https://user-images.githubusercontent.com/39287217/49059081-f8ca8380-f1bb-11e8-997f-a941f25031e2.png)

![screen shot 2018-11-26 at 8 15 40 pm](https://user-images.githubusercontent.com/39287217/49059084-fc5e0a80-f1bb-11e8-92e1-fce140b8297c.png)

**Comment by TeddyCr** [comment]
@eliselkin, sound good. This has been transferred to the frontend repo.
