### ISSUE TITLE
Merge Staging To Master

### ISSUE THREAD

**Issue by TeddyCr** [hackla-engage/engage-client#175]
@joshbeme / @eliselkin  could we merge staging into master? The staging version is many enhancements ahead of prod. It would be good to release these new features and design updates.

**Comment by eselkin** [comment]
I have no problem with it. I was deferring to @owenjoseph, but I think it would be good to merge unless there's a test going on.

**Comment by TeddyCr** [comment]
Thanks @eselkin for merging this. Thank you very much @joshbeme for all the work on the front end so far. 

You are definitely making a difference in advancing the development of the frontend.
