### ISSUE TITLE
User should be able to register position from the Agenda Detail page using a popup Form (formerly called 'Vote form')

### ISSUE THREAD

**Issue by adamcee** [hackla-engage/engage-client#28]
** UPDATE AS OF June 26**
Mockup:

- User should be able to click on one of 3 buttons on the Agenda Item Page (Agree, Disagree, Need more info) and open a modal popup form  (link to mockup)

- User should not be able to submit the form without an email address

- User should be able to see the title of the agenda item on the form

- User should be able to add comment, name, demographic info, in addition to email.

- Form should show the ID of the Agenda Item

link to video of flow
https://www.youtube.com/watch?v=crD0EXfXYjc&feature=youtu.be

**Link to the mockups **
(click agree to open the popup and start the flow)
https://invis.io/TBLW94HE9MR#/304303933_Agenda_Detail_Page__-_XLG_-_Default_

Here is a link to just the form, click submit on the form to see more flow
https://invis.io/RNLW97Z6XDP#/304817527_Modals_-_Comment_Agree_Copy

** Previous Info Below**
Working proto/mvp of vote form

Vote form (mini survey with vote and comment field, to be emailed to council; includes user email field) User votes on Recommended Action, fills out comment field if desired, fills out brief demographic survey including zip code and maybe email. [many items do not have recommended actions or discrete summaries…should we only allow forms on items that have those things]

https://docs.google.com/document/d/19YzAdn1bi2khqk13Cd7qVs9g7KHhuEPIOLdJVfltxcI/edit

**Comment by adamcee** [comment]
@eselkin believe this is what you are doing in add-form branch?

**Comment by eselkin** [comment]
And it's marginally complete.

**Comment by EzDesigns** [comment]
AS A user
I WANT see the full agenda item
SO THAT I can read it and vote por/ con the RA. 

GIVEN I vote
WHENI click the button
THEN I am directed to input my demograpfic information

See image: 
![agenda item form screen](https://user-images.githubusercontent.com/30360266/39728924-288b3c70-520e-11e8-8883-e69a6555d54a.png)

**Comment by owenjoseph** [comment]
@eselkin there was a suggestion last night to add a "no position" vote option to this feedback form. Some constituents might not have a clear pro/con stance on a given proposal, but instead may just want to offer suggestions to clarify or add to the recommended action.

Also, is this data going anywhere at the moment?

**Comment by owenjoseph** [comment]
@EzDesigns hey Eric, is this attached mockup intended for the Android app?

**Comment by eselkin** [comment]
@owenjoseph I asked about that mockup and whether the form should be attached to agenda item or not. Nobody got back to me on that... It seems odd to have it attached, but not so odd. I can add a no-position to the form... I can change the boolean in the database to an integer and make more than 3 options if needed.

**Comment by owenjoseph** [comment]
@eselkin I'm convinced a three-position option is the way to go for the MVP, even if I'm still not settled on exact language for the third option:

1. Pro
2. Con
3. either "Need More Info" or "Comment only (no position)"

Does the new clickthrough from Emil Wing clarify the other point about which point in the flow is a modal and which is a page?

**Comment by eselkin** [comment]
Closed in #95
