### ISSUE TITLE
Feed of Agenda Items

### ISSUE THREAD

**Issue by adamcee** [hackla-engage/engage-client#29]
Working proto / mvp of feed of agenda items

Feed of agenda items (scraped from council website). User scrolls through agenda items, clicks one that interests them, goes to detail page.

https://docs.google.com/document/d/19YzAdn1bi2khqk13Cd7qVs9g7KHhuEPIOLdJVfltxcI/edit

**Comment by dorachan2000** [comment]
Done with #33
