### ISSUE TITLE
Set up React component for tutorial page

### ISSUE THREAD

**Issue by dorachan2000** [hackla-engage/engage-client#3]
Background:
How the city council works and how people can participate either directly at the meeting or through engage aren't really clear. It would be nice if there was a tutorials page that covers basics for people who aren't familiar with the process.

Requirement:
It could start with a React Component that simply displays html like a website. It should contain information about city council and engage. We could add interactions afterwards.

**Comment by owenjoseph** [comment]
@dorachan2000 can this be closed?

**Comment by dorachan2000** [comment]
@owenjoseph this was a ticket to create a tutorial page to describe how city council works and how people can participate either directly at the meeting or through engage. It's valuable for people who aren't familiar with the process so I would recommend leaving it open.

**Comment by owenjoseph** [comment]
Ahh, gotcha. So we need some copy. I'll work on this.

**Comment by owenjoseph** [comment]
@dorachan2000 could the "About" and/or "FAQ" pages be reworded to serve this purpose? The copy there is already in need of a refresh - I think the FAQ in particular could be reworded to meet the needs of a tutorial.

**Comment by dorachan2000** [comment]
@owenjoseph sure that could work

**Comment by owenjoseph** [comment]
Following is proposed copy for a new "How To" component.

# How to use Engage
On our main feed, you’ll see a list of all the most-recently posted Council Meeting Agenda Items from the City of Santa Monica. Each item includes a title describing the issue, and the date and time of the Council Meeting when that item will be discussed. To view an Agenda Item in more detail, click on “View Item” for that Agenda Item.

[Img1]

You’ll see the Executive Summary of the proposed item, as well as the City’s recommended action. Here is where you can enter a position on the recommended action: “Pro,” “Con,” or, if you don’t understand the issue, or want more information, “No Position.”

[Img2]

You can also share this issue with your friends and neighbors on social media or over email.

[Img3]

Once you enter a position, you’ll have a chance to confirm before submitting, as well as enter an optional comment and/or demographic information that the city can use to help better respond to your concerns. One required piece of information is an email address to which you have access. You’ll see why in a second. When you’re ready, click “Submit.”

[Img4]

Ahh, see that? Now we send an email to the address you provided. Time to head on over to your email account.

[Img5]

Follow the link in the email and your address will be logged in our system as “confirmed.” This way the City knows this feedback was submitted by an actual concerned citizen, and not a clever algorithm.

[Img6]


Public feedback will be closed at noon the day of the scheduled council meeting. At this point, the feedback entered on Engage for all that meeting’s Agenda Items are gathered into a report, which then gets sent to the City clerk’s office. This report is also made immediately available to the public, so you’ll be able to see the same data that Engage is sending to the City.

[Img7]
 
# How does the Santa Monica City Council Work?
The city council meets every other Tuesday (there are some exceptions) for public hearings and discussions. Agenda Items for each meeting are made public a minimum of 72 hours in advance of the scheduled meeting, and public feedback is accepted on these Items until noon the day of the Council Meeting.

More information about the City Council Meetings, and the Council itself, can be found at the City’s official Council Website, here: https://www.smgov.net/departments/council/

# Optional Copy / Content

City Council meetings are public – and you should go! But if you can’t, there are a number of ways to follow what’s happening, both during the meeting, and afterward.

KCRW

Video

Agenda Minutes

**Comment by owenjoseph** [comment]
2nd draft with images:

# How to use Engage
On our main feed, you’ll see a list of all the most-recently posted Council Meeting Agenda Items from the City of Santa Monica. Each item includes a title describing the issue, and the date and time of the Council Meeting when that item will be discussed. To view an Agenda Item in more detail, click on “View Item” for that Agenda Item.

![engage_howto_img1](https://user-images.githubusercontent.com/39287217/45277421-8e3b5e80-b47c-11e8-8af3-e8bade5d68cc.png)

You’ll see the Executive Summary of the proposed item, as well as the City’s recommended action. Here is where you can enter a position on the recommended action: “Pro,” “Con,” or, if you don’t understand the issue, or want more information, “No Position.”

![engage_howto_img2](https://user-images.githubusercontent.com/39287217/45277440-a3b08880-b47c-11e8-9323-34bf8d3e752e.png)

Once you enter a position, you’ll have a chance to enter an optional comment and/or demographic information that the city can use to help better respond to your concerns. *One required piece of information at this step is an email address to which you have access.* You’ll see why in a second. When you’re done, click “Submit.”

![engage_howto_img3](https://user-images.githubusercontent.com/39287217/45277477-de1a2580-b47c-11e8-9b08-bf9ca8644185.png)

This is your chance to review all your information before submitting to the City Clerk's office. You can edit what's entered, or – if you're ready – click this final "Submit" button.

![engage_howto_img4](https://user-images.githubusercontent.com/39287217/45277562-70222e00-b47d-11e8-999c-b661dbcd8f97.png)

Now we send an email to the address you provided. Time to head on over to your email account.

![engage_howto_img5](https://user-images.githubusercontent.com/39287217/45277597-afe91580-b47d-11e8-98cb-c0d14015c5d9.png)

Follow the link in the email and your address will be logged in our system as “confirmed.” This way the City knows this feedback was submitted by an actual concerned citizen, and not a clever algorithm.

![engage_howto_img6](https://user-images.githubusercontent.com/39287217/45277604-c2634f00-b47d-11e8-8e80-45c98f8d7036.png)

Public feedback will be closed at noon the day of the scheduled council meeting. At this point, the feedback entered on Engage for all that meeting’s Agenda Items are gathered into a report, which then gets sent to the City clerk’s office. This report is also made immediately available to the public, so you’ll be able to see the same data that Engage is sending to the City.

[Img7 (pending)]

# How does the Santa Monica City Council Work?
The city council meets every other Tuesday (there are some exceptions) for public hearings and discussions. Agenda Items for each meeting are made public a minimum of 72 hours in advance of the scheduled meeting, and public feedback is accepted on these Items until noon the day of the Council Meeting.

More information about the City Council Meetings, and the Council itself, can be found at the City’s official Council Website, here: https://www.smgov.net/departments/council/
