### ISSUE TITLE
Splash page

### ISSUE THREAD

**Issue by adamcee** [hackla-engage/engage-client#30]
Working proto / mvp of splash page

Splash page - no sign in. User clicks a link, lands on splash page, takes user to list of topics.

https://docs.google.com/document/d/19YzAdn1bi2khqk13Cd7qVs9g7KHhuEPIOLdJVfltxcI/edit

**Comment by dorachan2000** [comment]
Implemented with current landing page. "Click to Engage" button will take you to the feed
