### ISSUE TITLE
Mobile - Landing page

### ISSUE THREAD

**Issue by danielbaruch** [hackla-engage/engage-client#36]
**User Story:**
As a Santa Monica Resident, I want to open the app and land on a page that provides me an explanation as to what the app does, so that I may navigate the app knowing how to use the app.

**Notes:**
1. Please see the attached Mockup for the "Engage Landing Page"
2. Please note that a button called "Explore" must be added to the bottom of the page so that the user may navigate to the next page.
3. Description on Landing Page:
-- "Engage is a platform to make it easier for locals to participate in their local government with up-to-date issue provided by your City Council."
4. Please note that there is no sign-in option at this time. 
5. Google Analytics should also be setup on the Landing Page (see #7).

**Acceptance Criteria:**
1. As a Santa Monica Resident, Download the App
2. Open the App
3. Expected result is for a landing page to appear with a description as to what the app does.

**Questions:**
1. @EzDesigns asks - Where should the button on the landing page take the user to? - It should land on the Feed page (See ticket #36).

**Attachments:**
1. Mockup for Landing Page - 
![image](https://user-images.githubusercontent.com/30360266/39736176-e100d4ca-5233-11e8-8303-d12f05ee5164.png)

**Technical Approach:**

**Comment by EzDesigns** [comment]
![prototype landing](https://user-images.githubusercontent.com/30360266/39735947-b92e1602-5232-11e8-9665-dcc44af413e9.png)
