### ISSUE TITLE
Mobile - Item Feed page

### ISSUE THREAD

**Issue by danielbaruch** [hackla-engage/engage-client#38]
**User Story:**
As a Santa Monica Resident, I want to see all the active Items that are currently open with the Santa Monica City Council Members are currently reviewing, so that I may view the open issues.

**Notes:**
1. The user will navigate to the Item Feed by selecting the Landing Feed (#36) button.
2. The feed will have individual "Item Card" stacked on top of each other. 
3. Each "Item Card" will have the following fields populated and visible to the user:
--Hearing Date
--Hearing Time
--Item Title
4. Each Item will have a "View Item" and "Share" button that must be visible to the user.
5. If the above fields are not populated the card should not be displayed.
6. There will be a Menu button at the upper right hand corner of the screen to access menu items such as (About, FAQ, Exit).

**Acceptance Criteria:**
1. The Santa Monica Resident installs the app
2. Opens the App
3. Lands on the Landing Page, selects the button at the bottom of the page
4. Lands on the Items feed
5. Items feed contains Items that have all their fields populated fully and a menu button in the upper right hand corner of the page. 

**Questions:**
1. @EzDesigns asks - Should the buttons on the Items navigate to a new window or hover over the Items Feed? - 

**Attachments:**
1. Mockup

**Technical Approach:**
![agenda feed copy_mvp](https://user-images.githubusercontent.com/30360266/39881876-0bc0f78a-5437-11e8-89c6-be898d249a74.png)

**Comment by dorachan2000** [comment]
@EzDesigns do we want this landing page to come after people click "Click to Engage" button on the main website?
https://engage-santa-monica.herokuapp.com/#/

**Comment by dorachan2000** [comment]
implemented with #56
