### ISSUE TITLE
Mobile - Item Card details on the Item Feed

### ISSUE THREAD

**Issue by danielbaruch** [hackla-engage/engage-client#40]
User Story:
As a Santa Monica Resident, I want to select one of the Item Cards on the Item Feed (#38) that contains a quick summary of the Santa Monica City Council Members current item, so that I may have the option to view the Issue Card and select the Issue Card.

**Notes:**
1. Please reference ticket #38 for details regarding the Items Feed format.
2. Each "Item Card" will have the following fields populated and visible to the user on the Item Feed (#38):
--Hearing Date
--Hearing Time
--Item Title
Each Item will have a "View Item" and "Share" button that must be visible to the user.
If the above fields are not populated the card should not be displayed.

Acceptance Criteria:
1. The Santa Monica Resident installs the app
2. Opens the App
3. Lands on the Landing Page, selects the button at the bottom of the page
4. Lands on the Items feed
5. Items feed contains Item Cards that have all their fields populated fully

Questions:
1. 

Attachments:
<img width="352" alt="screen shot 2018-05-11 at 12 37 28 am" src="https://user-images.githubusercontent.com/11156409/39912432-8d5ede20-54b3-11e8-8e6c-1aa064fc20ae.png">

**Comment by EzDesigns** [comment]
![mvp item card](https://user-images.githubusercontent.com/30360266/39907789-b715a064-549f-11e8-8eb0-4fa9641cf4e3.png)
