### ISSUE TITLE
Mobile - Voting Form on the Item Card page

### ISSUE THREAD

**Issue by danielbaruch** [hackla-engage/engage-client#42]
**User Story:**
As a Santa Monica Resident, I want vote on the Issue presented by the Santa Monica City Council Members, so that I can voice my opinion in regards to an issue. 

**Notes:**
1. Required: Voting Form fields:
- First Name
- Last Name
- Email Address (email validation to be included)
2. Optional: Voting Form fields:
- Comments (Up to 250 characters)
- Zip Code (zip code validation where only residents in the Santa Monica area can vote on Santa Monica related Items)
3. Details for Santa Monica Zip Code Validation see: (http://www.city-data.com/zipmaps/Santa-Monica-California.html)
- 90291, 90401, 90402, 90403, 90404, 90405
4. Two buttons to be created:
- Pro 
- Con
5. Votes will need to be captured and associated with the Item Card that the User selected.
6. Popup to appear after a "Pro" or a "Con" is selected to verify the Users choice.

**Acceptance Criteria:**
1. The Santa Monica Resident installs the app
2. Opens the App
3. Lands on the Landing Page, selects the button at the bottom of the page
4. Lands on the Items feed
5. Select an Item Card from the Items Feed
6. New page opens with Item Card details including:
- Hearing Time
- Hearing Date
- Item Card Title
- Item Card Details (including "Executive Summary" and "Recommendation")
7. User enters in the following information: 
- First Name
- Last Name
- Email Address (email validation to be included)
- Comments (Up to 250 characters)
- Zip Code (Santa Monica only)
8. User votes on either Pro or Con options
9. Popup verifying choice of either Pro or Con.
- If user selects "No", on popup, they go back to Item Card page
- If User selects "Yes", on popup, user is notified with "Submitted" on the popup.

**Questions:**
1. @danielbaruch is asking - How are we going to ensure that each user can only vote on one issue, one time? - 
2. @danielbaruch is asking - Do we want to add an email validation? - 
3. @danielbaruch is asking - Do we want to add Zip code validation? - 
4. @danielbaruch is asking - Do we want to have a popup to verify the Users selection of their Pro/Con choice? - 
5. @danielbaruch is asking - Do we want to validate form submissions with CAPTCHA? - 

**Attachments:**
![agenda item view](https://user-images.githubusercontent.com/30360266/39907071-38c40a88-549b-11e8-8cff-8f7c9a9b537d.png)

**Comment by eselkin** [comment]
Branch add-form

Pro/Con is part of 6
Email is validated on the form.
Zip is somewhat validated (to valid US zip codes)
The form will show a prominent pro/con banner on the top of the form.
Captcha is being used now

**Comment by owenjoseph** [comment]
@eliselkin can this issue be closed? Seems stale and/or satisfied.
