### ISSUE TITLE
Master AgendaItem cards

### ISSUE THREAD

**Issue by eselkin** [hackla-engage/engage-client#54]
Distorted cards after clicking from feed on mobile:

<img width="376" alt="distorted_cards" src="https://user-images.githubusercontent.com/5606931/39973538-c1eafede-56d5-11e8-8c09-3d0bc5922a59.png">

**Comment by dorachan2000** [comment]
@EzDesigns will update the mocks to have a mobile friendly version and then @evalineBai can adjust this screen
