### ISSUE TITLE
Dynamically load more agendas in the feed page

### ISSUE THREAD

**Issue by dorachan2000** [hackla-engage/engage-client#58]
Background:
Currently, the feed page only hits the following API endpoint once and loads the initial batch of agendas.
https://council-tag.herokuapp.com/api/agendas/

We should use the pagination endpoint provided in the API endpoint such as,
https://council-tag.herokuapp.com/api/agendas/?limit=2&offset=2

Requirement
- At the bottom of the feed, create a "Load More" button
- Once you click the "Load More" button, more agendas will load from the pagination API Endpoint

**Comment by JerryLeeCS** [comment]
I am thinking about storing NEXT in Redux state, and use it in action creator. I am not sure if it's a good approach.

**Comment by JerryLeeCS** [comment]
API has a problem with endpoint "/" that would return same url in next.
For example
With API call
`https://council-tag.herokuapp.com/api/agendas/?limit=2&offset=2 `
returns
`"next": "https://council-tag.herokuapp.com/api/agendas/?limit=2&offset=4"`
But with API call from async.js
`https://council-tag.herokuapp.com/api/agendas/?limit=2&offset=2/ `(With an extra / at the end of URL) 
returns with 
`"next": "https://council-tag.herokuapp.com/api/agendas/?limit=2&offset=2" `
which doesn't return the next page
