### ISSUE TITLE
When viewing Item Detail Card, browser "back" button does not behave as expected

### ISSUE THREAD

**Issue by adamcee** [hackla-engage/engage-client#63]
when viewing the item detail card, pressing the back button does not take the user back to the feed. As the URL changes when viewing an item detail card (an id query param is added to it with the id of the card in question), and as clicking the back button does change the URL, it should also mimic the behavior of taking the user back to the previous "screen" (i.e. the feed).

To Reproduce:
1. Open this URL: http://localhost:8080/#/feed?id=40
2. Press the "back" button on your browser. 
3. Note that the URL has changed to: http://localhost:8080/#/feed -- this is the URL to view the Feed.

Expected behavior:
 - The Item Detail Card disappears and the user is returned to the feed.
Actual behavior:
 - The Item Detail Card does not disappear.

**Comment by owenjoseph** [comment]
Hey @adamcee, is this a product of the feed item being presented as a popup modal? Right now a user has to click on the "x" to close. I'm not sure this is the best flow.

@dorachan2000 I feel strongly this should be changed from a modal to a full navigation page, but I heard your concerns last night and agree we need to mockup a full user flow before committing to any big changes like that.

**Comment by dorachan2000** [comment]
@owenjoseph yes removing modal window should involve ux decision and more people.

**Comment by altaf933** [comment]
I don't see any feeds , modal keep loading but no any response. Is something doing wrong with api ?

**Comment by owenjoseph** [comment]
I'm closing this – new site flow and design have solved this issue.
