### ISSUE TITLE
Clicking on agenda item should redirect to its own page with (vs layover currently)

### ISSUE THREAD

**Issue by TeddyCr** [hackla-engage/engage-client#71]
The feed workflow creates a layover when an agenda item is clicked. This needs to be converted to have the agenda item open its own page where the title, the summary, the recommended action, the form to comment and the buttons to vote will be present.

see flowchart: https://drive.google.com/open?id=1AMAM6kQbJwRsrdQ3kzUalWkAmooO5Jeq

see mocks: https://projects.invisionapp.com/share/NBLKJ4AZ82Q#/304303934_Homepage__-_XLG_-_Def

-- User should be able to click title text to link to the Agenda Item Detail Page
-- User should be able to click CTA to link to the agenda Item detail page
-- User should be able to click date/time to link to the agenda Item Page

link to video of flow
https://www.youtube.com/watch?v=crD0EXfXYjc&feature=youtu.be

**Link to the mockups **
(click agree to open the popup and start the flow)
https://invis.io/TBLW94HE9MR#/304303933_Agenda_Detail_Page__-_XLG_-_Default_

**Comment by JerryLeeCS** [comment]
https://github.com/hackla-engage/engage-client/pull/84

**Comment by JerryLeeCS** [comment]
The code is merged
