### ISSUE TITLE
"For", "against", "Don't understand" buttons need to be added to the feed item boxes

### ISSUE THREAD

**Issue by TeddyCr** [hackla-engage/engage-client#72]
3 buttons need to be added to the item box in the feed ("For", "against", "Don't understand") allowing to tally the votes for each issue (regardless a comment was posted on the issue or not). The number of comments should also be displayed.

Ideally, if a user hits a button, she/he should be suggested learn more about the issue and submit a comment

**Comment by eselkin** [comment]
This should have been added as well to the backend repo as an issue. @TeddyCr, you want to add it or should I? Currently there's no way to get a total tally, but I can make one.

**Comment by eselkin** [comment]
I can't remember who completed this issue, but it is done. #95 uses the number values of 0=con, 1=pro, 2=need more info and sends to the backend in that format.
