### ISSUE TITLE
Update agenda feed page based on last mock-up

### ISSUE THREAD

**Issue by TeddyCr** [hackla-engage/engage-client#73]
The agenda items feed design needs to be updated to match the most recent mocks: https://projects.invisionapp.com/share/NBLKJ4AZ82Q#/304303934_Homepage__-_XLG_-_Default_

-- User should be able to see a list of upcoming agenda items sorted by Datetime Ascending

-- Note...the mockup  shows "saved" and "suggested"....ignore for now and do not add those parts.

**Comment by owenjoseph** [comment]
This is essentially solved.
