### ISSUE TITLE
User should see a confirmation page when verifying email

### ISSUE THREAD

**Issue by iamemilywing** [hackla-engage/engage-client#75]
When user receives a confirmation link, he/she should click through and see a confirmation page that tells them the email is confirmed.

This page should link back to the agenda feed. 

Mockup:
https://invis.io/5DLW79JVQ7U#/304921726_Email_Confirmation__-_XLG_-_Default_

link to video of flow
https://www.youtube.com/watch?v=crD0EXfXYjc&feature=youtu.be

**Comment by dorachan2000** [comment]
Impelmented through #81
