### ISSUE TITLE
User should be directed to a popup requesting them to check email for confirmation link if submitting with an unverified email

### ISSUE THREAD

**Issue by iamemilywing** [hackla-engage/engage-client#76]
And "unverified" email is one that has not been confirmed to belong to the submitter.

Mockups here
https://invis.io/SRLW8AEX2QC#/304662123_Modals_-_Comment_Step_3_Confirmation_Unverified

**Comment by owenjoseph** [comment]
Hey @allysonw is this one in progress?

**Comment by allysonw** [comment]
@owenjoseph Hi there, sorry I somehow didn't see this was assigned to me at all. I have not started on it. I'll likely be taking a break from this project for a bit. Can you assign it to someone else? Thanks!

**Comment by owenjoseph** [comment]
No prob, @allysonw. Thanks for you contributions!

**Comment by eselkin** [comment]
Kind of done in #95
