### ISSUE TITLE
User should be directed to confirm their submission of a Position

### ISSUE THREAD

**Issue by iamemilywing** [hackla-engage/engage-client#77]
After submitting the Register Position Form, User should see a popup where he/she is asked to confirm data before submitting. 

link to mockups
https://invis.io/98LW8TOGFKA#/304662124_Modals_-_Comment_Step_2

link to video of flow
https://www.youtube.com/watch?v=crD0EXfXYjc&feature=youtu.be

**Comment by eselkin** [comment]
complete #95
