### ISSUE TITLE
User should be able to generate a share URL for each proposal.

### ISSUE THREAD

**Issue by owenjoseph** [hackla-engage/engage-client#78]
User should see an option to create or copy a share URL when they click into each Proposal Page. 

For the MVP, this URL should be suitable for sharing on any Social platform or email (platform agnostic). 

Potential roadmap features would include a smart URL which offers link-back insights.

**Comment by TeddyCr** [comment]
Facebook shared link needs to be fixed as it does not currently lead to anything. Refer to PR #90.

**Comment by owenjoseph** [comment]
unassigning this for pickup

**Comment by owenjoseph** [comment]
This issue is satisfied by #139
