### ISSUE TITLE
User should not need to sign in to comment

### ISSUE THREAD

**Issue by owenjoseph** [hackla-engage/engage-client#89]
This user sign-in is a remnant of an outdated MVP design. 

2-part acceptance criteria:

- User should not be presented with sign-in option
- User should not have to be signed in in order to submit comments or any other data related to the proposal feedback submission

![remove-signin](https://user-images.githubusercontent.com/39287217/43434446-7eadd09a-9430-11e8-933c-057bcb45d52d.png)

**Comment by eselkin** [comment]
Does that mean it's a requirement, doesn't seem to mean that.

**Comment by owenjoseph** [comment]
I do think this removing the login flow should be a requirement for MVP launch, if that's what you mean?

**Comment by owenjoseph** [comment]
Hey @eselkin let me know if you think I need to clarify this issue further.

**Comment by eselkin** [comment]
Oh, there's no login flow for MVP, I don't think at the moment... I just think that word is there for no reason.

**Comment by owenjoseph** [comment]
@eselkin gotcha; removed
